#!/usr/bin/env bash
set -euo pipefail

: "${RAG_FLOW_COMPILE_JOBS:=20}"
: "${RAG_FLOW_RUNTIME_THREADS:=8}"

cat >> ~/.bashrc <<EOF

# --- RAG Flow CPU threading ---
export MAX_JOBS=$RAG_FLOW_COMPILE_JOBS
export MAKEFLAGS="-j$RAG_FLOW_COMPILE_JOBS"
export NINJA_JOBS=$RAG_FLOW_COMPILE_JOBS
export OMP_NUM_THREADS=$RAG_FLOW_RUNTIME_THREADS
export MKL_NUM_THREADS=$RAG_FLOW_RUNTIME_THREADS
export OPENBLAS_NUM_THREADS=$RAG_FLOW_RUNTIME_THREADS
export VECLIB_MAXIMUM_THREADS=$RAG_FLOW_RUNTIME_THREADS
export NUMEXPR_NUM_THREADS=$RAG_FLOW_RUNTIME_THREADS
# --------------------------------
EOF
